{% set cleanupCommand = 'apt-get clean; rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*' %}
{% spaceless %}
    {% if phpVersion == '7.0.x' %}
        {% set image = 'phpdockerio/php7-fpm:latest' %}
    {% elseif phpVersion == '7.1.x' %}
        {% set image = 'phpdockerio/php71-fpm:latest' %}
    {% else %}
        {% set image = 'phpdockerio/php56-fpm:latest' %}
    {% endif %}
FROM {{ image }}

{% if extensionPackages %}
# Install selected extensions and other stuff
RUN apt-get update \
    && apt-get -y --no-install-recommends install {% for package in extensionPackages %} {{ package }}{% endfor %} \
    && {{ cleanupCommand }}
{% endif %}

{% if applicationType == 'phalcon' %}
# Install phalcon
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 1E569794 \
    && echo "deb http://ppa.launchpad.net/phalcon/stable/ubuntu wily main" > /etc/apt/sources.list.d/phalcon.list \
    && apt-get update \
    && apt-get install php5-phalcon \
    && php5enmod phalcon \
    && {{ cleanupCommand }}
{% endif %}

WORKDIR "{{ workdir }}"
{% endspaceless %}
