{% set cleanupCommand = 'apt-get clean; rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*' %}
{% spaceless %}
    {% if phpVersion == '7.0.x' %}
        {% set image = 'phpdockerio/php7-fpm:latest' %}
    {% elseif phpVersion == '7.1.x' %}
        {% set image = 'phpdockerio/php71-fpm:latest' %}
    {% elseif phpVersion == '7.2.x' %}
        {% set image = 'phpdockerio/php72-fpm:latest' %}
    {% elseif phpVersion == '7.3.x' %}
        {% set image = 'phpdockerio/php73-fpm:latest' %}
    {% elseif phpVersion == '7.4.x' %}
        {% set image = 'phpdockerio/php74-fpm:latest' %}
    {% else %}
        {% set image = 'phpdockerio/php56-fpm:latest' %}
    {% endif %}
FROM {{ image }}
WORKDIR "/application"

# Fix debconf warnings upon build
ARG DEBIAN_FRONTEND=noninteractive

{% if extensionPackages %}
# Install selected extensions and other stuff
RUN apt-get update \
    && apt-get -y --no-install-recommends install {% for package in extensionPackages %} {{ package }}{% endfor %} \
    && {{ cleanupCommand }}
{% endif %}

{% if hasGit %}
# Install git
RUN apt-get update \
    && apt-get -y install git \
    && {{ cleanupCommand }}
{% endif %}

{% endspaceless %}
