FROM php:fpm

RUN apt-get update

RUN apt-get -y install zlib1g-dev libmemcached-dev

RUN docker-php-ext-install opcache

RUN docker-php-ext-install zip

# Memcached
RUN curl -sS https://codeload.github.com/php-memcached-dev/php-memcached/tar.gz/php7 -o /usr/src/php/ext/memcached.tgz \
    && tar -xf /usr/src/php/ext/memcached.tgz -C /usr/src/php/ext/ \
    && rm /usr/src/php/ext/memcached.tgz \
    && docker-php-ext-install php-memcached-php7

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Symfony tmp folders
RUN mkdir -p /tmp/phpdocker.io/cache
RUN mkdir -p /tmp/phpdocker.io/logs
RUN mkdir -p /tmp/phpdocker.io/sessions
RUN chown www-data:www-data /tmp/phpdocker.io

WORKDIR /var/www/phpdocker.io
