{% spaceless %}
    {% if phpVersion == '7.0.x' %}
        FROM phpdockerio/php7-fpm:latest
    {% else %}
        FROM phpdockerio/php56-fpm:latest
    {% endif %}
{% endspaceless %}


{% if extensionPackages %}
# Install selected extensions
RUN apt-get update \
    && apt-get -y --no-install-recommends install {% for package in extensionPackages %} {{ package }}{% endfor %} \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
{% endif %}

{% if isSymfonyApp %}
# If you're using symfony and the vagranted environment, I strongly recommend you change your AppKernel to use the following temporary folders
# for cache, logs and sessions, otherwise application performance may suffer due to these being shared over NFS back to the host
RUN mkdir -p "/tmp/{{ projectNameSlug }}/cache" \
    && mkdir -p "/tmp/{{ projectNameSlug }}/logs" \
    && mkdir -p "/tmp/{{ projectNameSlug }}/sessions" \
    && chown www-data:www-data -R "/tmp/{{ projectNameSlug }}"
{% endif %}

WORKDIR "{{ workdir }}"
