FROM php:fpm

RUN apt-get update

# Install extension dependencies, plus atool for custom extension unpacking
RUN apt-get -y install atool zlib1g-dev {% for dependency in dependencies %}{{ dependency }} {% endfor %}

# Install zip for composer's benefit
RUN docker-php-ext-install zip

# Install selected extensions
{% for extension in stdExtensions %}
RUN docker-php-ext-install {{ extension }}
{% endfor %}

# Install custom extensions
{% for customDist in customDists %}
    {% include 'install-custom-php-ext.conf.twig' with {'tarballUrl': customDist.tarballUrl, 'uncompressedFolder': customDist.uncompressedFolder} only %}
{% endfor %}

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

{% if isSymfonyApp %}
# If you're using symfony and the vagranted environment, I strongly recommend you change your AppKernel to use the following temporary folders
# for cache, logs and sessions, otherwise application performance may suffer due to these being shared over NFS back to the host
RUN mkdir -p "/tmp/{{ projectName }}/cache"
RUN mkdir -p "/tmp/{{ projectName }}/logs"
RUN mkdir -p "/tmp/{{ projectName }}/sessions"
RUN chown www-data:www-data -R "/tmp/{{ projectName }}"
{% endif %}

WORKDIR "{{ workdir }}"
