FROM phpdockerio/php7-fpm:latest

# If you're using symfony and the vagranted environment, I strongly recommend you change your AppKernel to use the following temporary folders
# for cache, logs and sessions, otherwise application performance may suffer due to these being shared over NFS back to the host
RUN mkdir -p "/tmp/phpdocker-io/cache" \
    && mkdir -p "/tmp/phpdocker-io/logs" \
    && mkdir -p "/tmp/phpdocker-io/sessions" \
    && chown www-data:www-data -R "/tmp/phpdocker-io"

WORKDIR "/var/www/phpdocker-io"
