name: "Test application"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  # Allow workflow to be manually run from the GitHub UI
  workflow_dispatch:

jobs:
  tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "dir=$(make composer-cache-dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Initialise environment
        run: make prep-ci

      - name: Run static analysis
        run: make static-analysis

      - name: Run unit and functional tests
        run: make unit-tests

      - name: Cleanup
        if: always()
        run: make clean
